### ISSUE TITLE
Add Promise.reject() for handle auth errors and close auth window (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [eddiemoore/angular-spotify#23]
How is possible to add callback function when auth popup authentication is closed by user?

```js
$Spotify.login().then(function (data) {
  if (data) {
  } else {
     
  }
})

// maybe like this:
.error(function () {
  console.log("User has canceled auth popup!");
});
```
Regards.

**Comment by eddiemoore** [comment]
At the moment it doesn't reject that Promise. Do you need it for a specific task?

**Comment by joseluisq** [comment]
Yes, In fact I solved yesterday this to adding `Promise.reject()` 
and some minor updates in your `NgSpotify.login()` function.
I have renamed issue title (enhancement)
So I will send a pull request about this soon.
Regard.

**Comment by joseluisq** [comment]
#24 :+1:
