### ISSUE TITLE
bower version is out of date

### ISSUE THREAD

**Issue by simonghales** [eddiemoore/angular-spotify#30]
Hey eddiemoore,

Thanks for putting this together, it's been rather useful.

I just encountered an issue however when I try to use the getCategories function.

It seems that the version of angular-spotify available over bower hasn't had its /dist/ file updated to the latest changes. I can see the getCategories function in the /src/js file, but not the /dist/js file.

Cheers,

Simon

**Comment by eddiemoore** [comment]
Thanks for letting me know. Can you try reinstalling it from bower now?

**Comment by simonghales** [comment]
Looks like it's done the trick. Thank you!

**Comment by eddiemoore** [comment]
:+1: Thanks

**Comment by simonghales** [comment]
Hey man just a heads up I don't think your latest updates are live on bower

**Comment by eddiemoore** [comment]
@simonghales :( damn bower. Anyway should be fixed now. Thanks.
