### ISSUE TITLE
SpotifyProvider.setAuthToken later in life cycle

### ISSUE THREAD

**Issue by cleechtech** [eddiemoore/angular-spotify#31]
After I login I get back a token and have it saved in localStorage:

```
app.controller('MainCtrl', function($scope, $http, $window, $rootScope, Spotify, SpotifyProvider){
	$rootScope.token = $window.localStorage.getItem('spotify-token') || false;

	$scope.requestSpotifyLogin = function(){
		Spotify.login().then(function(data){
			$rootScope.token = data;
		});
	};
});
```

Then when I send a request  like (`Spotify.userFollowingContains('type', 'ids')`) I get an error that my request is not authorized even though I am logged in:

```
GET https://api.spotify.com/v1/me/following/contains?ids=ids&type=type 401 (Unauthorized)
```

I think that is because I have not set my auth token with `SpotifyProvider.setAuthToken('zoasliu1248sdfuiknuha7882iu4rnuwehifskmkiuwhjg23');`. However when the Provider phase runs I do not have a token.

What I would like to do is `Spotify.setAuthToken($rootScope.token)` and maybe `Spotify.getAuthToken()` so that once a user logs in I can begin authorizing requests

**Comment by simonghales** [comment]
You should be able to set the auth token outside of config? Currently I set mine after checking to see if the cookie is stored, in a run block.

`
if($cookies.get('spotify-token')) {
      Spotify.setAuthToken($cookies.get('spotify-token'));
}
`

**Comment by cleechtech** [comment]
Ok that works! Thank you
