### ISSUE TITLE
how to setRedirectUri based on environment?

### ISSUE THREAD

**Issue by cleechtech** [eddiemoore/angular-spotify#33]
I am using `SpotifyProvider.setRedirectUri` in my app.config block like so:

```
SpotifyProvider.setRedirectUri('http://localhost:3000/api/spotify/callback');
```

Now I have deployed my application to heroku at http://showjunkie.herokuapp.com/#/. How can I conditionally set the rederict uri based on the environment? I don't want the production env to point to localhost but it is nice for development

**Comment by eddiemoore** [comment]
One way to do it would be 
```js
var redirectURL = window.location.href.indexOf('localhost') > -1 ? 'http://localhost:3000/api/spotify/callback' : 'http://showjunkie.herokuapp.com/api/spotify/callback';
SpotifyProvider.setRedirectUri(redirectURL);
```

So if the location includes localhost use the localhost url, otherwise use the production url

**Comment by cleechtech** [comment]
omg you're a genius. I was working on sending my server side config variables to angular and parsing those. This is much better solution. Great project btw
