### ISSUE TITLE
rederict callback window not closing on heroku deploy

### ISSUE THREAD

**Issue by cleechtech** [eddiemoore/angular-spotify#34]
When I log in with spotify everything works peachy on localhost. However for my heroku deploy I will log in to spotify and the callback.html will appear with an access token in the url string, but the box does not close itself. LocalStorage is updated on the callback.html but not for the main site, index.html

![screen shot 2015-11-20 at 11 24 31 am](https://cloud.githubusercontent.com/assets/3578908/11309595/94ee92ae-8f79-11e5-93a9-d7cd71412f75.png)

The issue is that in production the callback.html box does not go away by itself after contacting spotify successfully. It works when running on localhost though..

**Comment by eddiemoore** [comment]
Hmm. I haven't run into that issue before.
In the callback page once it updates the local storage then you could add a ```window.close()```.

**Comment by cleechtech** [comment]
Now it works. This went away after a few minutes with the heroku deploy. Either that or I was using $cookies instead of localStorage
