### ISSUE TITLE
Can't get latest version from Bower?

### ISSUE THREAD

**Issue by mokargas** [eddiemoore/angular-spotify#45]
For some reason, calling "bower install angular-spotify --save" on Mac OSX will only retrieve 1.3.0. Same issue if I do "bower install angular-spotify#1.4.0 --save" directly

Dump:

bower not-cached    https://github.com/eddiemoore/angular-spotify.git#1.4.0
bower resolve       https://github.com/eddiemoore/angular-spotify.git#1.4.0
bower ENORESTARGET  No tag found that was able to satisfy 1.4.0

Additional error details:
Available versions in https://github.com/eddiemoore/angular-spotify.git: 1.3.0, 1.2.1, 1.2.0, 1.1.1, 1.0.0, 0.14.0, 0.13.0, 0.12.0, 0.11.0, 0.10.0, 0.9.3, 0.8.1, 0.8.0, 0.7.0, 0.6.0, 0.5.4, 0.5.0, 0.3.0, 0.1.15, 0.1.14, 0.1.13, 0.1.12, 0.1.11, 0.1.10

**Comment by eddiemoore** [comment]
I just created a new release package @mokargas can you try again?

**Comment by mokargas** [comment]
All good Eddie, thank you very much. That's gotta hold the record for the fastest resolution ever on GH.

One more suggestion:

"bower invalid-meta  The "main" field cannot contain minified files"

Might be better to put the non-dist version in the main file.

**Comment by eddiemoore** [comment]
@mokargas Ok thanks will check on that.
