### ISSUE TITLE
Missing Token for Audio Feature Methods

### ISSUE THREAD

**Issue by felixroos** [eddiemoore/angular-spotify#47]
Hi there, thanks for this dope library!
Everything works fine except getting the audio features of a track (tempo, danceability etc..). The problem is, that the methods `getTrackAudioFeatures` and `getTracksAudioFeatures` do not send an access token, which is required, see [spotify api docs for audio-features](https://developer.spotify.com/web-api/get-audio-features/).

A simple fix could be:

Line 474, change
```javascript
return this.api('/audio-features/' + track);
```
to
```javascript
return this.api('/audio-features/' + track, 'GET', null, null, this._auth());
```
this will send the token in the header!

Similar need to append this._auth() to `getTracksAudioFeatures`. 

I could send a PR if you want!

Have a nice day,
Felix

**Comment by eddiemoore** [comment]
Thanks for spotting the bug. Will fix it within the next day

**Comment by eddiemoore** [comment]
Hey @felixroos sorry for the delay.
Updated the package with the fix.

**Comment by felixroos** [comment]
thanks a lot!
