### ISSUE TITLE
Can't login. New windown doesn't close.

### ISSUE THREAD

**Issue by italo-batista** [eddiemoore/angular-spotify#52]
Hello everybody.

I'm using angular v1.6.4 and [angular-spotify](https://github.com/eddiemoore/angular-spotify/blob/master/src/angular-spotify.js) for angular 1.6.

I'm just trying to login. Until now, my app just should do that. So I don't have much code. I'm using all code provided as example in this repository, just for learning.

My callback.html looks like just as in the bottom of the README page.

My problem is: I can't login or I can't get the token. When I press the login button, the login window is created. I insert my credentials. But after, in the same login window, I am redirected to my app home. So I remain with two windows in my app home. When I force to close the window that was created when I pressed the login button, I verify that the login wasn't successful.

[My code](https://github.com/italo-batista/spotifyme).

Can somebody help me? I don't know if it is a bug or if I am missing something.

**Comment by danielpersonius** [comment]
Did you resolve this?
