### ISSUE TITLE
From May 29 all requests to our Web API will require authentication

### ISSUE THREAD

**Issue by sensodejay** [eddiemoore/angular-spotify#53]
On 29th May 2017 the /search /tracks /albums /artists and /users (and related) endpoints will start requiring an access token, bringing them in-line with all other Web API endpoints.

https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/

**Comment by scottiejibbs** [comment]
This "bit" me this yesterday, so it did go into effect.  I wasn't up on the "news", so it was a surprise for me last night when I started seeing 401's.   Fortunately, just minor updates required to the angular-spotify service.   For example, the "artists" endpoint - just requires including the auth (see below)  Gave a try this morning and works fine:

return this.api('/artists/', 'GET', { ids: artists ? artists.toString() : '' }, **null, this._auth()**);

**Comment by eddiemoore** [comment]
Sorry for the late response. Was meaning to update this earlier but fell sick for a while.
All should work now
